# Stage 1: Build the application
FROM node:18-alpine AS builder

WORKDIR /app

COPY ../app/package*.json .
RUN npm install

COPY ../app .
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Change working directory within the image
WORKDIR /usr/share/nginx/html

# Remove default Nginx static assets
RUN rm -rf ./*

# Copy the built application from the builder stage
COPY --from=builder /app/dist .

# Start Nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
