FROM node:18-alpine AS builder

COPY app/package*.json .
RUN npm install

COPY ./app .
RUN npm run build

# setup the Nginx server for production
FROM nginx:alpine
# change working directory within the image
WORKDIR /usr/share/nginx/html
# remove default nginx static assets
RUN rm -rf ./*
# copy the built application from the builder stage
COPY --from=builder ./app .

# start Nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
