version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env
  api:
    build:
      context: ../backend
      dockerfile: deploy/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ../backend/.env
    depends_on:
      - db
  ui:
    build:
      context: ../frontend
      dockerfile: deploy/Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - api
  
volumes:
  postgres_data:
