"""added submission_time

Revision ID: d236ca4eb141
Revises: 
Create Date: 2024-04-19 20:34:17.097269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd236ca4eb141'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('submission_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'submission', ['student_id', 'test_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='unique')
    op.drop_column('submission', 'submission_time')
    # ### end Alembic commands ###
