FROM python:3.11 as base

# Create a non-root user and build/run the app
RUN useradd --create-home appuser
WORKDIR /app
RUN chown appuser /app
USER appuser
COPY --chown=appuser requirements.txt ./
RUN pip install --no-cache-dir --timeout=1200 -r requirements.txt
EXPOSE 8000

CMD ["python3", "app.py"]
